[project]
site_name = "Пешачко"
site_description = "Пешачко -- инициатива за чист въздух и здраве."
site_author = "Димитър Димитров (drdv.github.io)"
site_url = "https://peshachko.bg/"
repo_url = "https://github.com/peshachko/peshachko.github.io"
edit_uri = "edit/main/docs/"
copyright = """&copy; 2025 НПО Пешачко"""
extra_css = ["stylesheets/extra.css", "stylesheets/glightbox.min.css"]

nav = [
  {"Начало" = "index.md"},
  {"НПО" = "ngo.md"},
  {"Събития" = [
    "events/events.md",
	{"Минали" = [
	  {"22 Септември 2025" = "events/20250922_event.md"},
	  {"12 Август 2025" = "events/20250812_event.md"}]},
	]},
  {"Нашият град" = "environment.md"}
]

# ----------------------------------------------------------------------------
# Section for configuring theme options
# ----------------------------------------------------------------------------
[project.theme]
language = "bg"
favicon = "img/logo.png"
logo = "img/logo.png"
custom_dir = "docs/overrides"

features = [
    # "announce.dismiss",
	"content.action.edit",
    "content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "header.autohide",
    "navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    # "navigation.path",
    # "navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    # "toc.follow",
    # "toc.integrate",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.extra]
generator = false

[[project.extra_javascript]]
path = "javascripts/glightbox.min.js"

[[project.extra_javascript]]
path = "javascripts/glightbox_load.js"
type = "module"
